### ISSUE TITLE
What happened to the individual libraries?

### ISSUE THREAD

**Issue by RGBboy** [transduce/transduce#1]
Just found that a bunch of your libraries have been unpublished on npm. I really liked being able to cherry pick just the functionality I need for an application. Why the change?

**Comment by kevinbeaty** [comment]
Yeah.... sorry about that.  I didn't think anyone would notice as I had so few downloads :)  I was up to 30+ single function libraries, and it ended up being a pain to maintain. Every time I wanted to make a change in a base library, I had to update so many dependencies (yes, I could probably script it).

My initial motivation for maintaining separate modules was to minimize size when using `browserify`, but then I realized I could do the same thing with requiring paths from `transduce` ... `require('transduce-array')` just becomes `require('transduce/array')`.  In fact, I broke up `transduce-array` into individual functions, so you can `require('transduce/array/slice')` and only get that single function (and dependencies) in the `browserify` bundle. If you want it all, you can `require('transduce')`.

So you can still cherry pick the functionality you need ... knowing that, does that help?  Are there other reasons you likes the separate modules outside client bundles?

**Comment by RGBboy** [comment]
Yeah thats a great solution, just don't go rearranging the directory structure too often. 

The other reason I prefer separate, small modules is that it helps document the functionality you are using. Just by reading the require statements at the top of a file I can see exactly what functionality I am using. 

PS thanks for your work on transducers, especially your blog posts. They helped me a lot to  wrap my head around the concept.

**Comment by kevinbeaty** [comment]
Yup.  I don't plan on moving anything around.

I also like the explicit require of the functions you need.  I updated `underscore-transducer` and other dependent libraries to specify the path the the functions, but I could see people just wanting to import the whole library.

No problem.  I'm happy that you found them helpful.
