### ISSUE TITLE
Shortcut for wrapping transformer

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#13]
I find myself doing this quite a bit when writing custom transducers / transformers

```js
var t = require('transduce')
module.exports = function(xf) {
  return {
    init: () => xf.init(),
    step: function(result, val) {
      // custom step function
    },
    result: (val) => xf.result(val)
  }
}
```

Is there any sort of helper yet to make this simpler, or am I missing something else obvious about why I might not need this?

**Comment by kevinbeaty** [comment]
I think this is a good idea.  It certainly is a common pattern.  Would you like to make a PR?

**Comment by kevinbeaty** [comment]
Here is an option:

```javascript
function step(rf) {
  return function(xf){
    return new Step(rf, xf)
  }
}
function Step(rf, xf) {
  this.xf = xf
  this.step = rf
}
Step.prototype.init = function(){
  return this.xf.init()
}
Step.prototype.result = function(result){
  return this.xf.result(result)
}
```

Usage:

```javascript
function map(f) {
  return step(function(result, input){
    return this.xf.step(result, f(input))
  })
}

function takeWhile(p){
  return step(function(result, item){
    return p(item) ? this.xf.step(result, item) : reduced(result)
  })
}

function drop(n){
  return step(function(result, item){
    if(this.n === void 0) this.n = n

    if(--this.n < 0){
      result = this.xf.step(result, item)
    }
    return result
  })
}
```

It feels a little awkward and I can't think of a better name...  Thoughts?

**Comment by kevinbeaty** [comment]
Or "uncurrying" `xf` for the common use case:

```javascript
function map(f) {
  return step(function(xf, result, input){
    return xf.step(result, f(input))
  })
}

function takeWhile(p){
  return step(function(xf, result, item){
    return p(item) ? xf.step(result, item) : reduced(result)
  })
}

function drop(n){
  return step(function(xf, result, item){
    if(this.n === void 0) this.n = n
    if(--this.n < 0){
      result = xf.step(result, item)
    }
    return result
  })
}

function step(xfStep) {
  return function(xf){
    return new Step(xfStep, xf)
  }
}
function Step(xfStep, xf) {
  this.xf = xf
  this.xfStep = xfStep
}
Step.prototype.init = function(){
  return this.xf.init()
}
Step.prototype.step = function(result, input){
  return this.xfStep.call(this, this.xf, result, input)
}
Step.prototype.result = function(result){
  return this.xf.result(result)
}
```

**Comment by tgriesser** [comment]
I'd probably vote the second - seems like it'd be more flexible, and using a context via `this.xf.step` feels a bit awkward.

Not sure about a name, I guess step seems alright although kind of vague.

**Comment by tgriesser** [comment]
Playing around with this a bit and it's quite nice. I'd be :+1 on adding the last form suggested.

**Comment by kevinbeaty** [comment]
Sounds good.   I'm a bit hung up on the name and where it should belong.   I don't really want `base` to become too large but I don't think it fits anywhere else. It's probably OK there.

If you come up with any good names, let me know.

**Comment by tgriesser** [comment]
So I was actually going to ask about the composition of `base`. I actually don't see too much wrong with having a lot of things on the root namespace a-la underscore, however from a require path standpoint it might make more sense to actually split functionality into a "core" (`reduce`, `transduce`, `iterator`, `isReduced`, `unreduced`, `completing`) and then into a transducers directory, since the individual transducers are for the most part stand alone.

Right now there's a lot of circular dependencies between the different core functionality so there's actually nothing gained by modularizing and IMO it's a bit confusing to have a separate namespace for some of the transformer / iterator pieces that are used frequently. 

Keeping things like transduce and reduce in the same file would also allow you to do take some small shortcuts like:

```js
function _reduce(xf, init, coll) {
  if(isArray(coll)){
    return arrayReduce(xf, init, coll)
  }
  if(isFunction(coll.reduce)){
    return methodReduce(xf, init, coll)
  }
  return iteratorReduce(xf, init, coll)
}
function reduce(xf, init, coll){
  if(isFunction(xf)){
    xf = completing(xf)
  }
  if (arguments.length === 2) {
    coll = init
    init = xf.init()
  }
  return _reduce(xf, init, coll)
}
function transduce(t, xf, init, coll) {
  if (isFunction(xf)){
    xf = completing(xf)
  }
  xf = t(xf)
  if (arguments.length === 3) {
    coll = init;
    init = xf.init();
  }
  return _reduce(xf, init, coll)
}
```

With an internal shared `_reduce` to skip the extra `isFunction` and `arguments.length` checks and such in the transduce -> reduce step.

**Comment by kevinbeaty** [comment]
Yeah, I was thinking about separating the transducers from the other base/core functionality.  I really do like requiring the functions directly though, especially when using browserify.  I think that is one thing that distinguishes this library from the more popular ones. I don't think there is any harm in including "private" functions like `_reduce` alongside the "public" functions (distinguished by `_` prefix). 

 I tried to avoid circular dependencies, can you point me to a few examples?

I've considered flattening everything into one namespace as well ... but things like `join` can mean different things in different contexts  which is why I didn't do that initially.  (I might want to add a `join` to work with `by` from #11 but haven't thought that through yet).  Still might be a good way to go though.

@RGBBoy Any thoughts on reorganization? I know you would like to maintain the explicit require for builds, and I promised you I wouldn't move things around much :)

```javascript
core = {
reduce: function(xf, init?, coll)
transduce: function(t, xf, init?, coll)
eduction: function(t, coll)
into: function(init, t?, coll?)
sequence: function(t, coll) // this should move now to core now that we are using it in eduction
toArray: function(t?, coll?)
toObject: function(t?, coll?)
toString: function(t?, coll?)
compose: function(/*fns*/)
isReduced: function(value)
reduced: function(value, force?)
unreduced: function(value)
// anything else?
}

transducers = {
map: function(f)
filter: function(predicate)
remove: function(predicate)
take: function(n)
takeWhile: function(predicate)
drop: function(n)
dropWhile: function(predicate)
cat: transducer
mapcat: function(f)
partitionAll: function(n)
partitionBy: function(f)
transformStep: function(f)
}

```

**Comment by tgriesser** [comment]
> I tried to avoid circular dependencies, can you point me to a few examples?

Sorry not really circular dependencies, but just like shared dependencies... like if you're requiring `reduce` you're always going to get `iterator`, which means you're always going to get `iterable`, etc... so if the goal is to shave browserify bits you're not gaining anything (and actually probably losing a small bit overall)

Whereas it'd be totally possible to have the inverse where `require('transduce/core/reduce')` was internally just proxied to `module.exports = require('../core').reduce`, and then where you'd really win is requiring the individual transducers by hand, since right now requiring base comes with `drop` or `dropWhile` even if I don't use those.

> I've considered flattening everything into one namespace as well ...

Yeah, I would agree this isn't worth it. Just main pieces that are practical 90% of the time (the core stuff, the any top-level transducing fns, and some of the transformer / iterator functionality) would make sense to keep on the default base namespace. Internally they could still be mapped to individual files as it makes sense for browserify - especially the transducers.

I like the idea of having namespaces for main pieces like `array`, `string`, `push`, `math` - I think some of the `transformer` utility fns is what I was thinking of for core, and maybe `iterable` / `iterator` / `isIterator`.

> I think that is one thing that distinguishes this library from the more popular ones. 

I'd say the distinguishing factor is this library is much further along than the others and more well planned out / maintained. Great work.

**Comment by kevinbeaty** [comment]
Added `transducers/transformStep`

**Comment by kevinbeaty** [comment]
Version 0.6.0
