### ISSUE TITLE
Support Official Transformer Protocol

### ISSUE THREAD

**Issue by kevinbeaty** [transduce/transduce#25]
Change to the "transformer protocol" suggestion from @tgriesser in cognitect/transducers-js#20 with `@@transformer` property and returning function instead of object.

Of course, if any "standard" is agreed upon, that would be better.

**Comment by kevinbeaty** [comment]
Also consider making `transformer` private and removing `protocols.transformer` (which would remove `protocols` entirely after #24 )

**Comment by tgriesser** [comment]
Looks like this is ready to implement:

https://github.com/cognitect-labs/transducers-js/blob/master/src/com/cognitect/transducers.js#L44-L64

**Comment by kevinbeaty** [comment]
@tgriesser Thanks for spearheading the specification of an official protocol.  I've updated my libraries to conform as well, and filed issues for other libraries that I know have already integrated transducers.

You may be interested to know that I redefined most transducers in terms of a modified `transformStep`, which is now `transducer` in `core` and supports `init` and `result` redefinitions as well.

**Comment by tgriesser** [comment]
Sounds good, except it looks like you left it off the top level namespace

**Comment by kevinbeaty** [comment]
@tgriesser Whoops.  Published 0.8.1 with exported `transducer` at top level and core
