### ISSUE TITLE
compatibility with ramda

### ISSUE THREAD

**Issue by queckezz** [transduce/transduce#28]
Awesome library you got going here. I haven't actually used it but i'm planning to. I have a couple of questions that i'm unsure about:

I saw your new [blog post](http://simplectic.com/blog/2015/ramda-transducers-logs/). You used Ramda there extensively together with your transducer library. Howewer, functions like `compose()` and a lot more are reimplemented in `transduce` itself. Are you planning to get rid of Ramda and rely only on `transduce`? If not, where are you going to cut the line between those two? 

I also saw https://github.com/ramda/ramda/pull/878. I'm not really a 100% sure where to get started with it. Please note that I haven't understood the whole concept about transducers yet and I might be missing something crucial here.

**Comment by kevinbeaty** [comment]
Thanks!

This library is interoperable with Ramda, so you can pick and choose features from either one.  The `compose` function in transduce is equivalent to `R.compose` in Ramda so they will behave the same.

> Are you planning to get rid of Ramda and rely on only transduce? If not, where are you going to cut the line between those two? 

Ramda is a great library for many reasons, even outside transducers, and is very well supported.  Now that they've added transducers, I have been contemplating what the separation should be.  I am currently thinking that I will keep the focus here only on transducers, and possibly incorporate functionality that may not belong in Ramda, but would be useful in other contexts. And also keep it as a playground to explore other related concepts before proposing them in Ramda.

Again, the good news is that you can pick and choose the functionality you like from either library, and use the transducers interchangeably. 

> I'm not really a 100% sure where to get started with it.

It's a difficult concept to grasp (at least it was for me), but I think it's a powerful concept once you do. There are a few suggestions for further reading/watching at the end of  the [blog post](http://simplectic.com/blog/2015/ramda-transducers-logs/) you mentioned. Just start playing around with things.  Pick something you are interested in and see where it leads.

**Comment by queckezz** [comment]
Thank's for the fast response!

Definitely going to mix and match the different libraries. Didn't know that, because your library is architectured a certain way, you can just require the parts you want.

I did understand the basic concept of transducers. One thing that i'm not really sure about is how to implement it with any data type. I think how transducers work is explained really good.

Let's say I have some sort of a channel concept:  `var ch = chan()`. I can `put()` values on it and `take()` values from it. How does let's say the transducer `map()` know which values to map over it? Somehow I need to be able to tell that it needs to push and take from `Channel.buffer`

I've seen `jlongster/transducer` which has a concept of `buildables`
```js
// make it buildable
Map.prototype['@@append'] = Map.prototype.add;
Map.prototype['@@empty'] = function() { return new Map(); };
Set.prototype['@@append'] = Set.prototype.add;
Set.prototype['@@empty'] = function() { return new Set(); };
```
[source](http://jlongster.com/Transducers.js--A-JavaScript-Library-for-Transformation-of-Data#Works-with-Everythin)

Again, maybe i'm missing something completely

**Comment by tgriesser** [comment]
That blog post looks to be a bit out of date, might want to read - the new [transformer protocol](https://github.com/cognitect-labs/transducers-js#transformer-protocol) replaces the `@@append` / `@@empty` of `buildables` with a standardized way of specifying how an object may built up / composed with other transformers.

**Comment by kevinbeaty** [comment]
You may want to check out [js-csp](https://github.com/ubolonton/js-csp) for an implementation of channels that support transducers.

For a custom implementation, you would create the Channel with a transducer.  The transducer would be initialized with a transformer that would put values on your channel in `@@transducer/step`. When you `put` a new value on a channel protected by a transducer, you would step it through the transformer using `@@transducer/step` (new API).  The transformer created from the transducer may or may not step values onto the underlying transformer that actually puts values on the channel.

For example, say you created a channel protected by a `filter(p)` transducer.  Only the values passing the predicate would be stepped to the wrapped transformer that actually puts the values on the channel. The values that do not pass the predicate would be dropped with the transformer created from `filter(p)`.

Does that make sense?

**Comment by kevinbeaty** [comment]
Note that the support for channels described above is a case of implementing a custom [transducible process](http://clojure.org/transducers#toc11).   See the custom `transduce` implementation in highland, kefir, RxJs, and transduce-stream, etc. for other examples.

For other data structures, it could be as simple as implementing `@@transducer/step`.   See [here](https://github.com/jlongster/transducers.js/#the-transducer-protocol) for an example supporting Immutable.js lists.

**Comment by kevinbeaty** [comment]
@queckezz Can we close this issue?  Certainly feel free to ask any more questions as you explore.

**Comment by queckezz** [comment]
Yes, thanks for the clarification! This helped a lot. I'm probably going to reread this thread, might be even good to reference this somewhere in the readme.
