### ISSUE TITLE
Infinite loop in sequence when list is exhausted

### ISSUE THREAD

**Issue by kevinbeaty** [transduce/transduce#30]
From #29 
@tgriesser  says: I'm pretty sure there's also a bug in the currently lazy sequence implementation. I've found it possible to get stuck in an infinite loop - it seems to not break when the list is exhausted. I didn't investigate too deeply but didn't have the same problem when using the code from transducers.js

**Comment by kevinbeaty** [comment]
@tgriesser Do you have a test case where this fails?  Thanks.

**Comment by tgriesser** [comment]
Yeah let me see if I can figure out what exactly was triggering this

**Comment by tgriesser** [comment]
I'm having a hard time reproducing, likely due to some attempts at mutating the values of `this.values` as I was playing around with lazy sequences. You can feel free to close and I'll reopen if I can figure out what situation got me here.

**Comment by kevinbeaty** [comment]
@tgriesser OK.  Will close for now. Definitely reopen if you run into again. Thanks.

**Comment by tgriesser** [comment]
I'm pretty sure this is what was causing it: https://github.com/transduce/transduce/pull/35#issuecomment-91072583
