### ISSUE TITLE
Code Splitting and Transducer Implementation Confusing

### ISSUE THREAD

**Issue by kevinbeaty** [transduce/transduce#31]
From @tgriesser in #29 
> One other thing I've noticed while trying to do things in the library currently, is that the code
splitting and binding/applying of context has made things very difficult to follow. It's difficult to know
what the value of "this" is, and almost might be easier if stuff was done functionally in places where the new transducer function is being utilized.

**Comment by kevinbeaty** [comment]
@tgriesser Can you expand on what you mean by this?

> almost might be easier if stuff was done functionally in places where the new transducer function is being utilized.

**Comment by tgriesser** [comment]
By functionally I mostly just meant without overusing dynamic `this`

Small example:

```js
function forEach(f) {
  return transducer(function(step, value, input){

    // What does "this" refer to here... not entirely clear... 
    // Sort of feels like an anti-pattern to do too much bind/applying
    // when there otherwise wouldn't be a context
    if(this.idx === void 0){
      this.idx = 0
    }
    f(input, this.idx++, value)
    return step(value, input)
  })
}
```

vs 

```js
function forEach(f) {
  var idx = 0;
  return transducer(function(step, value, input){
    f(input, idx++, value)
    return step(value, input)
  })
}
```

**Comment by kevinbeaty** [comment]
Oh, of course.  Seems obvious once someone points it out :)

**Comment by kevinbeaty** [comment]
One thing that does allow is to reuse `forEach` with multiple transformers though (to reinitialize the index)

**Comment by kevinbeaty** [comment]
Would something like this be better:
```javascript
function forEach(f) {
  return transducer(function(xf, value, input){
    if(xf.idx === void 0){
      ctx.idx = 0
    }
    f(input, xf.idx++, value)
    return xf.step(value, input)
  })
}
```

**Comment by tgriesser** [comment]
> One thing that does allow is to reuse forEach with multiple transformers though (to reinitialize the index)

Would you often be reusing the same forEach with different transformers though?

> Would something like this be better:

Potentially, yeah though it feel sort of nice to call `step(value, input)` 

Also it might be worth making a set of benchmarks (or copying over the ones from jlongsters) to see if/where any potential code shortcuts are advantageous / harmful. I personally tend to favor source code readability and execution speed more than file size.

**Comment by kevinbeaty** [comment]
> Would you often be reusing the same forEach with different transformers though?

Sure.  Any time you would create a transducer and reuse it on multiple arrays.

```javascript

var firstTwo = into([], take(2))
firstTwo([1, 2, 3])  // [1,2]
firstTwo([3, 4, 5])  // [3,4]
```

>  I personally tend to favor source code readability and execution speed more than file size.

It wasn't really about reducing file size, my motivation was just to reduce the redundancy in the implementation, and I liked how this one looked in the common case. But I can see it could be confusing outside my head.  Maybe there is a better way. Benchmarks would probably be a good idea.

**Comment by tgriesser** [comment]
> Sure. Any time you would create a transducer and reuse it on multiple arrays.

Ah right - then yeah I guess it does feel a little confusing then to be mutating the value of the `xf` for re-use in that manner. I'm guessing you're also losing a bit of the performance here running everything through a code path dependent on `apply`.

> It wasn't really about reducing file size, my motivation was just to reduce the redundancy in the implementation

I'm also not referring to the use of `transduce` so much as just the general splitting of files. I guess maybe I've been writing a lot of ES6 lately and realizing that I'd prefer to just say:

```js
import {into, transduce, map} from 'transduce'
```

But when going through and looking at the code it becomes a matter of knowing how all of the various require puzzle pieces and directory paths fit together rather than browsing through a few core files which have the main pieces I'd need to worry about.

I guess sometimes there's a tradeoff of the ability to read/reason about code that you lose a bit of when doing one function per-file (maybe it'd be possible to look at how lodash-cli is able to set up a build step to split a single file out into the explicit require paths you're looking to achieve).

**Comment by kevinbeaty** [comment]
> then yeah I guess it does feel a little confusing 
> you're also losing a bit of the performance here running everything through a code path dependent on apply.

I will probably end up just reverting to the old implementations with functions returning object instances, with updated API of course.  I'm not surprised someone brought up performance with the new implementation. I actually did think of it when changing the implementation. Just didn't think it would happen so fast :)

> rather than browsing through a few core files which have the main pieces I'd need to worry about.

Maybe you want to look [here](https://github.com/transduce/transduce/blob/master/build/transduce.js).  Just teasing.  I think I know what you mean, the multiple namespace mapping could certainly lead to confusion. Navigating multiple files never really bothered me much, but that might be evidence that I'm jaded by Java.

**Comment by kevinbeaty** [comment]
Curious to hear thoughts on #33 and #34 to see if implementing either or both would address the concerns  brought up in this issue.

**Comment by kevinbeaty** [comment]
@tgriesser OK to close this via #35 ?

**Comment by tgriesser** [comment]
Yep
