### ISSUE TITLE
Ideas for making better use of init

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#48]
So I've been thinking about this a bit... `transduce/init` in its current form is generally pretty useless. I'm wondering if it'd be possible to use make better use of `tInit` internally to be able to replace the need for instantiating with `new`, e.g.:

```js
// Note: this isn't currently possible, sort of a 
// contrived example
class List extends Immutable.List {
  static [tInit]() {
    return new this().asMutable()
  }
  [tInit]() {
    return new this.constructor()
  }
  [tStep](value, [key, value]) {
    return value.set(key, value)
  }
  [tReduce](value) {
    return value.asImmutable()
  }
}

into(List, [1, 2, 3, 4]) // List [1, 2, 3, 4]
```

Thoughts on that?

**Comment by kevinbeaty** [comment]
I agree. Although `@@transducer/init` is used in reduced arity forms of `transduce` and `reduce`. In your example `Immutable.List` could be used with these forms  and (I think) `tr.into(Immutable.List)` would work.  

Certainly interested in hearing any other thoughts that you have to make it more useful.

**Comment by tgriesser** [comment]
Closing in favor of #49
