### ISSUE TITLE
Sequence -> Seq

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#51]
So in transducers.js the `seq` function is pretty neat because it's essentially doing:

```js
seq(coll, t)
```

as shorthand for:

```js
into(__, t, coll)
```

where the `___` is automatically determined for you by the type of the `coll`... and actually as I'm writing this out I'm realizing why having an empty `init` is useful, for exactly this case.

Perhaps we're doing it wrong with `into`? if you want an immutable value you should just be responsible for doing that yourself?

Anyway, the `sequence` function as it stands right now always returns a `LazyIterator`, but it seems like this would be a much better behavior. Perhaps that could be renamed to `lazySeq` and called as the fallback for `seq` or `sequence`. Thoughts?

**Comment by kevinbeaty** [comment]
I took the `sequence` name (and behavior) from my understanding of the same named function in Clojure.  We could potentially get rid of it though in favor of `eduction` as that now provides the same behavior.

I'm not that excited about the `seq` function, but I don't think I would oppose it if you thought it was useful.

**Comment by kevinbeaty** [comment]
> I don't think I would oppose it if you thought it was useful.

Actually, maybe I would... Does `seq` really bring you much over a curried `into`?  You could just `into([]), into({}), into(Immutable.List())`, etc and use the curried function as `seq`.    The one thing it doesn't bring is the dispatch on the collection type, but how useful would that really be in practice?

**Comment by tgriesser** [comment]
> Does seq really bring you much over a curried into

Not sure, I'll reopen if I think of any good cases.
