### ISSUE TITLE
Question: how does transduce relate to transducers.js and transducers-js?

### ISSUE THREAD

**Issue by dypsilon** [transduce/transduce#57]
Hi, I'm wondering if transduce is using one of the aforementioned libraries internally or is it a rewrite/fork?

**Comment by kevinbeaty** [comment]
It's an alternative library, neither dependent nor a fork. It is, however, compatible with the "transducer protocol" and is compatible with any other library that makes use of transducers following the protocol (including transducers.js, transducers-js, RxJS, Highland.js, Ramda, etc.).

**Comment by dypsilon** [comment]
Thank you for the answer!
