### ISSUE TITLE
eduction

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#6]
Might be good to see if there's anything here around clojure's `eduction` that can be translated well to JS

http://clojure.github.io/clojure/branch-master/clojure.core-api.html#clojure.core/eduction

https://groups.google.com/forum/#!topic/clojure/Rv9vdcRp0ls

And introduced here:
https://www.youtube.com/watch?v=4KqUvG8HPYo#t=2432

**Comment by kevinbeaty** [comment]
Yeah, I remember looking at this when the "Inside Transducers" video came out and wasn't sure of the application.   Due you understand when you would use it over `transduce` or `sequence`?

**Comment by tgriesser** [comment]
I believe the idea here is sort of the inverse of sequence - partial application of a transducer without knowing what the value is that you're pouring into.

Instead of trying to actually call transduce eagerly, it'd just return something which can be reduced / transduced / iterated. It would know what values it's going to operate on each time (so it'd need to be careful to avoid mutations), just not where / how to put them. 

The contrived example assumes a [two argument form of into](clojure.github.io/clojure/branch-master/clojure.core-api.html#clojure.core/into) exists.

```js
var divisibleByTwo = t.educer(t.map((val) => {
  return [val, val % 2];
}), [1, 2, 3])

var y = t.into([], divisibleByTwo) // [[1, false], [2, true], [3, false]]
var z = t.into({}, divisibleByTwo) // {1: false, 2: true, 3: false}
```

Haven't had a real world use case yet but i'm sure one exists - I'll keep my eye out.

This would also likely require creating another type check internally as to whether the value is an "educer".

**Comment by kevinbeaty** [comment]
Thanks. That helps.  

Taking a look at the Clojure source, `Iterable` and `Seqable` are implemented in terms of `sequence`.  The implementation of [`transduce/array/sequence`](https://github.com/transduce/transduce/blob/master/iterator/sequence.js) returns a JavaScript iterable, so I think that gets us most of the way there.  Since `sequence` is an iterable, it should work with `into`, `transduce`, etc.

It also implements `IReduceInit`, that seems to indicate a collection that can reduce itself, which is used within `reduce`.  This is interesting.  I would think this could be supported by checking `typeof coll.reduce === "function"` and use appropriately within `reduce`.

**Comment by kevinbeaty** [comment]
@tgriesser Please review #9 and verify it matches your interpretation of eduction.

**Comment by kevinbeaty** [comment]
One thing to note in the Clojure source that I translated:

```clojure
 ;; NB (completing f) isolates completion of inner rf from outer rf
 (transduce xform (completing f) init coll))
```
Do you know the purpose of this isolation?  Seems like we're losing context on a function/xf that the user controls.  I'm thinking about leaving it out for now.

**Comment by kevinbeaty** [comment]
Also, do you think we should use a Symbol for `@@reduce` (or similar) or leave it as a duck-typed `reduce` method?

**Comment by tgriesser** [comment]
I'm thinking duck typing might be the way to go until anything is formalized... I'm still not entirely sold on the use/implementation of the `transformer` protocol, as it's not formalized anywhere other than @jlongster's blog post, and it's notably absent in the cognitect implementation.

I believe the point of the completing is to sort of lift a standard reduce function into a 3-form transformer, so you would want the implementation to be more like this:

```js
function completing(f, cb) {
  if (arguments.length === 1) {
     return completing(f, identity)
  }
  if (isFunction(f)) {
    return {
       step: f,
       result: cb
    }
  }
  return f;
}
```

That way it could be a general purpose util used elsewhere. It's use is currently mentioned in the clojure `transduce` function's docstring:

```text
f should be a reducing step function that accepts both 
1 and 2 arguments, if it accepts only 2 you can add 
the arity-1 with 'completing'.
```

**Comment by kevinbeaty** [comment]
Agreed on duck-typing `reduce` for now. This library supports duck-typing transformers in addition to the `transformer` protocol.

Sorry, I wasn't clear on my question regarding `completing`.   The current implementation of `reduce` (and `transduce` by extension) already lifts functions into 3-form transformers using `xf = transformer(xf)`, so I don't know if the use of `completing` within `eduction` really makes sense in this implementation.  Might as well just pass the transformer/reducing function through `transduce` and let `reduce` lift the function if necessary.

But this does mean that the duck-typed `reduce` method should expect a 3-form transformer and not a reducing function... does this sound OK to you?

**Comment by tgriesser** [comment]
Well, the `completing` might actually be useful to have around as a standard way of supplying a non-identity return value, so you could do `t.completing(reducer, fn)`

I was also going to ask your opinion about whether the `xf = transformer(xf)` is possibly located it in the wrong place. In the cases of reduce & transduce, the only valid value for `xf` should be either a transformer or a reducing method. So the use of `transformer` should really come in functions which are implemented in terms of reduce / transduce such as `into`, etc.

Also, can you give me an example of what you mean about the duck-typed `reduce` method not expecting a reducing function?

**Comment by tgriesser** [comment]
Also, as I'm thinking about it more...I wonder if it'd be more faithful to the clojure impl if the lifted 
reducer -> transformer didn't throw on init and instead just called the same function with no arguments. 

```
(transduce xform f (f) coll))
```

It'd just be up to the user to check `arguments.length` and handle accordingly... so:

```js
function FunctionTransformer(step){
  this.step = step
}
FunctionTransformer.prototype.init = function(){
  return this.step()
}
FunctionTransformer.prototype.step = function(result, input){
  return this.step(result, input)
}
FunctionTransformer.prototype.result = identity
```

**Comment by kevinbeaty** [comment]
You may be right about `xf = transformer(xf)` not belonging within `reduce`. The intended effect is to  handle the case of lifting a reducing function into a transformer using `FunctionTransformer`.  Although it does bring along unnecessary baggage if `xf` is neither a reducing function nor a transformer.  It might make sense to change it to `xf = completing(xf)` if `typeof xf === 'function'`.

I agree that `completing` may be useful as a general util, I'm just not sure if it makes sense to use completing within `eduction` if we always lift reducing functions into transformers in `reduce`.

I also agree that it would be good to follow the Clojure lead on `FunctionTransformer#init` instead of throwing an error.

> Also, can you give me an example of what you mean about the duck-typed reduce method not expecting a reducing function?

If the implementation of `reduce` uses duck typing to handle the `IReduceInit` dispatch from Clojure, and we lift reducing functions to transformers within `reduce`, then `xf` will be a transformer, not a reducing function:

```javascript
function reduce(xf, init, coll){
   xf = // lift reducing function using `transformer(xf)`, or `completing(xf)`

   // special case array
   if(isArray(coll)) return arrayReduce(xf, init, coll)

   // check duck typed reduce, reducing function already lifted to transformer
   // or should it pass `xf directly without lifting?
   if(isFunction(coll.reduce)){
     // should xf be a transformer or a reducing function?
     return coll.reduce(xf, init)
   }

   // reduce with iterator
   return iterableReduce(xf, init, coll);
}
```

**Comment by kevinbeaty** [comment]
I've pushed a new version in #9 in response to the discussion above with the following changes:

- `coll.reduce` is passed the `xf.step` reducing function within  `transduce/reduce`. `xf.result` is called before returning the result.
- Remove the `completing` wrapper within `Eduction` as we are already lifting reducing functions to transformers in `reduce`.

My rationale for this approach is that if we are duck-typing on an arbitrary `coll.reduce`, it makes more sense to pass a reducing function to match the traditional reduce contract as it would be more likely that an existing `reduce` implementation is defined in terms of a reducing function and not  a transformer.

**Comment by tgriesser** [comment]
Saw you just merged this.. sorry haven't had time to give my full thoughts on it yet, I actually wasn't entirely sure if we need to implement `coll.reduce` on Eduction.

Also, I believe that [this](https://github.com/transduce/transduce/commit/a6ed4bba1ede224f6b659a0d712eb896b14e1270#diff-4bc9a5fd3833c030a1416667a0470ac1R21) is going to be an issue since you lose the context of xf... you'd need:

```js
xf.result(coll.reduce(function(result, val) {
  return xf.step(result, val)
}, init))
```

**Comment by kevinbeaty** [comment]
Ha.  Sorry about that.  I did intend to run all the changes by you before closing this issue. I need to start being less sloppy now that you are keeping an eye on me :)

I actually just pushed a few more commits addressing other issues you brought up in this thread.  I've separated out the `transformer` implementations and based used `completing` within `transduce` and `reduce`.  I've also corrected potential issue of binding `step` that you noted.

> I actually wasn't entirely sure if we need to implement coll.reduce on Eduction.
I think it's beneficial.  It will allow skipping the intermediate creation of the iterator using `sequence` when "chaining" an `eduction` with `transduce`/`reduce`.  If we did not add `reduce`, I don't know if `eduction` provides much benefit over `sequence` directly.... What are your hesitations?

**Comment by tgriesser** [comment]
No worries, I'm not sure what all I was thinking about it exactly, except that maybe duck typing on `reduce` was going to cause potential issues with objects you wish not to use reduce but you want to use as iterables, so I was thinking that maybe coming up with some sort of protocol might be the way to go here...

But yeah, feel free to close this out if you'd like, if I have other issues I'll bring them up in another ticket.

**Comment by kevinbeaty** [comment]
I thought about that as well.  I guess the assumption would be that `reduce` would be preferred over `@@iterable` if both are provided.  Seems OK to me.  If you really want to use the iterable you could either wrap it or pass the iterator directly to bypass this.

Did you get a chance to review the other commit with `completing` and `transformer` changes?  I think this addresses everything you brought up in this thread. If so, I'll close it out.

**Comment by tgriesser** [comment]
So I got a chance to ask @swannodette about eduction at reactconf, and it turns out the real value is in the ability to compose additional transducers onto the original eduction and return a new value which will run the composed transformation pipeline over the value.

So I guess that helps clear up the use case, I'd assume you'd probably be able to use it anywhere you could use a normal value, just with the transformations applied as you pour the value from one type into another.

Haven't thought at all about what the implementation should look like with this in mind, just wanted to throw it out there.

**Comment by kevinbeaty** [comment]
Makes sense.  Thanks for clarifying. I've been casually following Reactconf from a distance.  Sounds like a bunch of great stuff.

I think we still may be on the right track with the implementation, which supports JavaScript iterables and iterators.  Can you think of another JS value type other than `iterable` that should be added to the `Eduction` interface?   Like Clojure, if an `Eduction` is passed to any function that expects a `coll`, it will dispatch on the `reduce` method within the instance.  This bypasses the unnecessary creation of the `sequence` iterable.

**Comment by kevinbeaty** [comment]
Closing for now.  `eduction` added in 0.5.2
